[Script Info]
; Script generated by Aegisub 3.2.2
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
PlayResX: 288
PlayResY: 160

[Aegisub Project Garbage]
Audio File: C:/Users/Administrator/Desktop/断水流_clip(1).mp4
Video File: C:/Users/Administrator/Desktop/断水流_clip(1).mp4
Video AR Mode: 4
Video AR Value: 1.800000
Active Line: 6
Video Position: 390

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.08,0:00:03.80,Default,,0,0,0,,${mx.sentences0}
Dialogue: 0,0:00:03.80,0:00:05.80,Default,,0,0,0,,${mx.sentences1}
Dialogue: 0,0:00:05.80,0:00:07.80,Default,,0,0,0,,${mx.sentences2}
Dialogue: 0,0:00:07.80,0:00:08.90,Default,,0,0,0,,${mx.sentences3}
Dialogue: 0,0:00:08.90,0:00:09.50,Default,,0,0,0,,${mx.sentences4}
Dialogue: 0,0:00:09.50,0:00:10.90,Default,,0,0,0,,${mx.sentences5}
Dialogue: 0,0:00:10.90,0:00:13.30,Default,,0,0,0,,${mx.sentences6}
Dialogue: 0,0:00:13.30,0:00:14.90,Default,,0,0,0,,${mx.sentences7}
Dialogue: 0,0:00:14.90,0:00:16.90,Default,,0,0,0,,${mx.sentences8}
